-- Photo 1
INSERT INTO PROFILEPICTURE
VALUES (1, '/pdp/1.jpg');

-- Photo 2
INSERT INTO PROFILEPICTURE
VALUES (2, '/pdp/2.jpg');

-- Photo 3
INSERT INTO PROFILEPICTURE
VALUES (3, '/pdp/3.jpg');

-- Photo 4
INSERT INTO PROFILEPICTURE
VALUES (4, '/pdp/4.jpg');